"""rename address

Revision ID: 240e76e07923
Revises: d71d32d574eb
Create Date: 2025-08-20 14:27:38.465419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240e76e07923'
down_revision = 'd71d32d574eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ### 

