"""rename department

Revision ID: d71d32d574eb
Revises: 8ec8f1bba92b
Create Date: 2025-08-20 14:22:53.913957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd71d32d574eb'
down_revision = '8ec8f1bba92b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ### 
